const departmans = [
    { departmentid: 1, department_name: "Havacılık Mühendisliği" },
    { departmentid: 2, department_name: "Mimarlık" },
    { departmentid: 3, department_name: "Yapay Zeka ve Veri Mühendisliği" },
    { departmentid: 4, department_name: "Uzay Mühendisliği" },
    { departmentid: 5, department_name: "Kimya Mühendisliği" },
    { departmentid: 6, department_name: "Kimya" },
    { departmentid: 7, department_name: "İnşaat Mühendisliği" },
    { departmentid: 8, department_name: "Kompozisyon Bölümü" },
    { departmentid: 9, department_name: "Bilgisayar Mühendisliği" },
    { departmentid: 10, department_name: "Kontrol ve Otomasyon Mühendisliği" },
    { departmentid: 11, department_name: "Ekonomi" },
    { departmentid: 12, department_name: "Elektrik Mühendisliği" },
    { departmentid: 13, department_name: "Elektronik ve Haberleşme Mühendisliği" },
    { departmentid: 14, department_name: "Çevre Mühendisliği" },
    { departmentid: 15, department_name: "Moda Tasarımı" },
    { departmentid: 16, department_name: "Gıda Mühendisliği" },
    { departmentid: 17, department_name: "Jeoloji Mühendisliği" },
    { departmentid: 18, department_name: "Geomatik Mühendisliği" },
    { departmentid: 19, department_name: "Jeofizik Mühendisliği" },
    { departmentid: 20, department_name: "Endüstriyel Tasarım" },
    { departmentid: 21, department_name: "Endüstri Mühendisliği" },
    { departmentid: 22, department_name: "Enstrüman Bölümü" },
    { departmentid: 23, department_name: "İç Mimarlık" },
    { departmentid: 24, department_name: "Peyzaj Mimarlığı" },
    { departmentid: 25, department_name: "Yönetim Mühendisliği" },
    { departmentid: 26, department_name: "Üretim Mühendisliği" },
    { departmentid: 27, department_name: "Gemi Makineleri Mühendisliği" },
    { departmentid: 28, department_name: "Deniz Ulaştırma ve İşletme Mühendisliği" },
    { departmentid: 29, department_name: "Matematik Mühendisliği" },
    { departmentid: 30, department_name: "Makine Mühendisliği" },
    { departmentid: 31, department_name: "Metalurji ve Malzeme Mühendisliği" },
    { departmentid: 32, department_name: "Meteoroloji Mühendisliği" },
    { departmentid: 33, department_name: "Maden İşleme Mühendisliği" },
    { departmentid: 34, department_name: "Maden Mühendisliği" },
    { departmentid: 35, department_name: "Moleküler Biyoloji ve Genetik" },
    { departmentid: 36, department_name: "Müzik Teknolojisi Bölümü" },
    { departmentid: 37, department_name: "Müzik Teorisi Bölümü" },
    { departmentid: 38, department_name: "Müzikoloji Bölümü" },
    { departmentid: 39, department_name: "Gemi İnşaatı ve Denizcilik Mühendisliği" },
    { departmentid: 40, department_name: "Petrol ve Doğalgaz Mühendisliği" },
    { departmentid: 41, department_name: "Fizik Mühendisliği" },
    { departmentid: 42, department_name: "Gemi İnşaatı ve Okyanus Mühendisliği" },
    { departmentid: 43, department_name: "Tekstil Geliştirme ve Pazarlama" },
    { departmentid: 44, department_name: "Tekstil Mühendisliği" },
    { departmentid: 45, department_name: "Türk Halk Dansları Bölümü" },
    { departmentid: 46, department_name: "Şehir ve Bölge Planlama" },
    { departmentid: 47, department_name: "Ses Eğitimi Bölümü" }
];

export default departmans;
