export const departments = [
    { department_id: 1, department_name: "Havacılık Mühendisliği" },
    { department_id: 2, department_name: "Mimarlık" },
    { department_id: 3, department_name: "Yapay Zeka ve Veri Mühendisliği" },
    { department_id: 4, department_name: "Uzay Mühendisliği" },
    { department_id: 5, department_name: "Kimya Mühendisliği" },
    { department_id: 6, department_name: "Kimya" },
    { department_id: 7, department_name: "İnşaat Mühendisliği" },
    { department_id: 8, department_name: "Kompozisyon Bölümü" },
    { department_id: 9, department_name: "Bilgisayar Mühendisliği" },
    { department_id: 10, department_name: "Kontrol ve Otomasyon Mühendisliği" },
    { department_id: 11, department_name: "Ekonomi" },
    { department_id: 12, department_name: "Elektrik Mühendisliği" },
    { department_id: 13, department_name: "Elektronik ve Haberleşme Mühendisliği" },
    { department_id: 14, department_name: "Çevre Mühendisliği" },
    { department_id: 15, department_name: "Moda Tasarımı" },
    { department_id: 16, department_name: "Gıda Mühendisliği" },
    { department_id: 17, department_name: "Jeoloji Mühendisliği" },
    { department_id: 18, department_name: "Geomatik Mühendisliği" },
    { department_id: 19, department_name: "Jeofizik Mühendisliği" },
    { department_id: 20, department_name: "Endüstriyel Tasarım" },
    { department_id: 21, department_name: "Endüstri Mühendisliği" },
    { department_id: 22, department_name: "Enstrüman Bölümü" },
    { department_id: 23, department_name: "İç Mimarlık" },
    { department_id: 24, department_name: "Peyzaj Mimarlığı" },
    { department_id: 25, department_name: "Yönetim Mühendisliği" },
    { department_id: 26, department_name: "Üretim Mühendisliği" },
    { department_id: 27, department_name: "Gemi Makineleri Mühendisliği" },
    { department_id: 28, department_name: "Deniz Ulaştırma ve İşletme Mühendisliği" },
    { department_id: 29, department_name: "Matematik Mühendisliği" },
    { department_id: 30, department_name: "Makine Mühendisliği" },
    { department_id: 31, department_name: "Metalurji ve Malzeme Mühendisliği" },
    { department_id: 32, department_name: "Meteoroloji Mühendisliği" },
    { department_id: 33, department_name: "Maden İşleme Mühendisliği" },
    { department_id: 34, department_name: "Maden Mühendisliği" },
    { department_id: 35, department_name: "Moleküler Biyoloji ve Genetik" },
    { department_id: 36, department_name: "Müzik Teknolojisi Bölümü" },
    { department_id: 37, department_name: "Müzik Teorisi Bölümü" },
    { department_id: 38, department_name: "Müzikoloji Bölümü" },
    { department_id: 39, department_name: "Gemi İnşaatı ve Denizcilik Mühendisliği" },
    { department_id: 40, department_name: "Petrol ve Doğalgaz Mühendisliği" },
    { department_id: 41, department_name: "Fizik Mühendisliği" },
    { department_id: 42, department_name: "Gemi İnşaatı ve Okyanus Mühendisliği" },
    { department_id: 43, department_name: "Tekstil Geliştirme ve Pazarlama" },
    { department_id: 44, department_name: "Tekstil Mühendisliği" },
    { department_id: 45, department_name: "Türk Halk Dansları Bölümü" },
    { department_id: 46, department_name: "Şehir ve Bölge Planlama" },
    { department_id: 47, department_name: "Ses Eğitimi Bölümü" }
];